Repository Programmers-3th-Team-Kim/travel-manager, pull requests merged in 2024-08, with the labels that each got.

#2 [Chore] FE: 프로젝트 세팅 및 의존성 설치
  .github/PULL_REQUEST_TEMPLATE.md
  frontend/.gitignore
  frontend/README.md
  frontend/eslint.config.js
  frontend/index.html
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/main.tsx
  frontend/src/vite-env.d.ts
  frontend/tsconfig.app.json
  frontend/tsconfig.json
  frontend/tsconfig.node.json
  frontend/vite.config.ts
  frontend/yarn.lock
Labels: environment

#3 [CHORE] FE 프로젝트 초기 설정
  frontend/.eslintrc.cjs
  frontend/.husky/pre-commit
  frontend/.prettierrc.json
  frontend/eslint.config.js
  frontend/package.json
  frontend/postcss.config.js
  frontend/src/main.tsx
  frontend/tailwind.config.js
  frontend/yarn.lock
Labels: environment

#12 [CHORE] (FE) vite-tsconfig-paths 설정
  frontend/package.json
  frontend/tsconfig.app.json
  frontend/vite.config.ts
  frontend/yarn.lock
Labels: environment

#15 [FEAT] (FE) 레이아웃 설정
  frontend/index.html
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/assets/fonts/NotoSansKR-Regular.woff
  frontend/src/assets/fonts/Ubuntu-Bold.woff
  frontend/src/assets/logo.svg
  frontend/src/components/common/LogoSection.tsx
  frontend/src/components/layout/index.tsx
  frontend/src/pages/AddPlanPage.tsx
  frontend/src/pages/LoginPage.tsx
  frontend/src/pages/NotFoundPage.tsx
  frontend/src/pages/PlanDetailPage.tsx
  frontend/src/pages/PlanListPage.tsx
  frontend/src/pages/index.ts
  frontend/src/routes/index.ts
  frontend/src/routes/router.tsx
  frontend/src/styles/global.css
  frontend/tailwind.config.js
  frontend/yarn.lock
Labels: enhancement, environment

#17 [FEAT] (FE) Header 컴포넌트 추가
  frontend/package.json
  frontend/src/components/common/LogoLink.tsx
  frontend/src/components/layout/Header.tsx
  frontend/src/components/layout/index.tsx
  frontend/tailwind.config.js
  frontend/yarn.lock
Labels: enhancement

#25 [FEAT] (FE/BE) 로그인 페이지 구현
  backend/src/auth/auth.controller.ts
  backend/src/auth/auth.service.ts
  backend/src/main.ts
  frontend/index.html
  frontend/package.json
  frontend/src/api/http.ts
  frontend/src/api/kakaoAuth.api.ts
  frontend/src/assets/images/LoadingSpinner.gif
  frontend/src/assets/images/kakao_login_medium_narrow.png
  frontend/src/components/common/LoadingSpinner.tsx
  frontend/src/hooks/useKakao.ts
  frontend/src/model/kakao.model.ts
  frontend/src/pages/KakaoLoginPage.tsx
  frontend/src/pages/LoginPage.tsx
  frontend/src/pages/index.ts
  frontend/src/routes/index.ts
  frontend/src/routes/router.tsx
  frontend/yarn.lock
Labels: enhancement

#38 [FEAT] (FE) 여행 추가 폼 상태관리
  frontend/package.json
  frontend/src/components/addPlan/MoveStepButtons/index.tsx
  frontend/src/components/addPlan/SetInfoForm/index.tsx
  frontend/src/components/common/Button.tsx
  frontend/src/components/common/Input.tsx
  frontend/src/components/layout/Header.tsx
  frontend/src/constants/errorMessage.ts
  frontend/src/store/createStoreWithMiddleware.ts
  frontend/src/store/plan.ts
  frontend/src/types/index.ts
  frontend/src/types/plan.ts
  frontend/yarn.lock
  package.json
  yarn.lock
Labels: enhancement

#46 chore: root에서 immer 제거 후 frontend에 설치
  frontend/package.json
  frontend/yarn.lock
Labels: bug, environment

#48 [FEAT] (FE) 여행 날짜 설정 ui 및 로직 추가
  frontend/package.json
  frontend/src/assets/fonts/NotoSansKR-Bold.woff
  frontend/src/components/addPlan/MoveStepButtons/index.tsx
  frontend/src/components/addPlan/SetDateForm.tsx
  frontend/src/components/addPlan/SetDateForm/index.tsx
  frontend/src/components/addPlan/SetInfoForm.tsx
  frontend/src/components/addPlan/SetInfoForm/index.tsx
  frontend/src/components/addPlan/SetPlaceForm/index.tsx
  frontend/src/components/common/Button.tsx
  frontend/src/components/common/DateRangePicker.tsx
  frontend/src/components/layout/Header.tsx
  frontend/src/pages/AddPlanPage.tsx
  frontend/src/styles/datePicker.css
  frontend/src/styles/global.css
  frontend/src/types/index.ts
  frontend/src/types/plan.ts
  frontend/src/utils/formatDate.ts
  frontend/yarn.lock
  package.json
  yarn.lock
Labels: enhancement

#52 [FEAT] (FE) 여행지, 날짜 추가 단계 통합
  frontend/src/components/addPlan/CheckPlan.tsx
  frontend/src/components/addPlan/PlaceButton/index.tsx
  frontend/src/components/addPlan/SelectPlaceModal/index.tsx
  frontend/src/components/addPlan/SetDateForm.tsx
  frontend/src/components/addPlan/SetInfoForm.tsx
  frontend/src/components/addPlan/SetPlaceAndDateForm.tsx
  frontend/src/components/addPlan/SetPlaceForm/index.tsx
  frontend/src/components/addPlan/Stepper/index.tsx
  frontend/src/components/common/DateRangePicker.tsx
  frontend/src/components/common/Modal.tsx
  frontend/src/components/common/index.ts
  frontend/src/components/layout/Header.tsx
  frontend/src/constants/colors.ts
  frontend/src/hooks/useModal.ts
  frontend/src/pages/AddPlanPage.tsx
  frontend/src/store/plan.ts
  frontend/src/types/index.ts
  frontend/src/types/plan.ts
Labels: enhancement

#39 [FEAT] (FE) axios Request Handler, auth Store 구현
  frontend/package.json
  frontend/src/api/http.ts
  frontend/src/api/kakaoAuth.api.ts
  frontend/src/api/kakaoAuth.ts
  frontend/src/api/setting.ts
  frontend/src/hooks/useKakao.ts
  frontend/src/hooks/useKakaoLogin.ts
  frontend/src/pages/KakaoLoginPage.tsx
  frontend/src/pages/LoginPage.tsx
  frontend/src/store/auth.ts
  frontend/src/types/index.ts
  frontend/src/types/kakao.ts
  frontend/yarn.lock
Labels: enhancement
